#!/usr/bin/env python3
import base64
import os
import subprocess
import sys


def decrypt_secret(encrypted_base64: str, private_key_path: str) -> str:
    # Decode base64 to binary
    try:
        encrypted_bytes = base64.b64decode(encrypted_base64)
    except Exception as e:
        raise ValueError(f"Failed to decode base64 input: {e}")

    # Use openssl pkeyutl to decrypt the content.
    # Pass the encrypted bytes via stdin.
    process = subprocess.Popen(
        ["openssl", "pkeyutl", "-decrypt", "-inkey", private_key_path],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )
    stdout, stderr = process.communicate(input=encrypted_bytes)
    if process.returncode != 0:
        raise RuntimeError(f"OpenSSL error: {stderr.decode('utf-8')}")
    
    return stdout.decode('utf-8')

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 tools/decrypt_secret.py <encrypted_base64_string> [private_key_path]")
        print("Or: echo '<encrypted_base64_string>' | python3 tools/decrypt_secret.py - [private_key_path]")
        sys.exit(1)

    encrypted_base64 = sys.argv[1].strip()
    private_key_path = "private_key.pem"

    if len(sys.argv) >= 3:
        private_key_path = sys.argv[2]

    # Handle reading from stdin if '-' is passed as the first argument
    if encrypted_base64 == "-":
        encrypted_base64 = sys.stdin.read().strip()

    if not os.path.exists(private_key_path):
        print(f"Error: Private key file '{private_key_path}' not found.", file=sys.stderr)
        print("Please ensure the private key generated by generate_keypair.py is available.", file=sys.stderr)
        sys.exit(1)

    try:
        decrypted = decrypt_secret(encrypted_base64, private_key_path)
        print("=== DECRYPTED SECRET ===")
        print(decrypted)
        print("========================")
    except Exception as e:
        print(f"Decryption failed: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
